### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by barichello** [srwalter/libsmartpen#6]
It may sound stupid, but I dont know how to install this lib and the smartpen-browser.

Any one could help me?

**Comment by srwalter** [comment]
Are you running Ubuntu?  If so there is a PPA you can use to install prebuilt binaries.

**Comment by barichello** [comment]
Yes, I am using ubuntu. What is the ppa?

**Comment by srwalter** [comment]
https://launchpad.net/~stevenrwalter/+archive/ubuntu/ppa

On Mon, Sep 14, 2015 at 2:29 PM, Leonardo Barichello <
notifications@github.com> wrote:

> Yes, I am using ubuntu. What is the ppa?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/srwalter/libsmartpen/issues/6#issuecomment-140167485>.
>



-- 
-Steven Walter <stevenrwalter@gmail.com>

**Comment by barichello** [comment]
Thank you!
But I am getting an error:

Traceback (most recent call last):
  File "/usr/bin/smartpen-browser.py", line 4, in <module>
    import pysmartpen
ImportError: No module named pysmartpen

Any idea?

**Comment by srwalter** [comment]
I'm not able to reproduce that error.  What version of Ubuntu are you
using?  14.04 LTS?

Please run these commands and give me the output:

dpkg -L libsmartpen

ldd /usr/lib/pyshared/python2.7/pysmartpen.so

Thanks!

On Mon, Sep 14, 2015 at 4:17 PM, Leonardo Barichello <
notifications@github.com> wrote:

> Thank you!
> But I am getting an error:
>
> Traceback (most recent call last):
> File "/usr/bin/smartpen-browser.py", line 4, in
> import pysmartpen
> ImportError: No module named pysmartpen
>
> Any idea?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/srwalter/libsmartpen/issues/6#issuecomment-140194141>.
>



-- 
-Steven Walter <stevenrwalter@gmail.com>

**Comment by barichello** [comment]
I am using kubuntu 15.04.

dpkg -L libsmartpen gave me:

/.
/usr
/usr/share
/usr/share/python-support
/usr/share/python-support/libsmartpen.public
/usr/share/doc
/usr/share/doc/libsmartpen
/usr/share/doc/libsmartpen/copyright
/usr/share/doc/libsmartpen/changelog.Debian.gz
/usr/share/pyshared
/usr/share/pyshared/pysmartpen-0.0.0.egg-info
/usr/share/pyshared/parsestf.py
/usr/lib
/usr/lib/libsmartpen.so
/usr/lib/pyshared
/usr/lib/pyshared/python2.7
/usr/lib/pyshared/python2.7/pysmartpen.so
/lib
/lib/udev
/lib/udev/rules.d
/lib/udev/rules.d/75-smartpen.rules

And ldd /usr/lib/pyshared/python2.7/pysmartpen.so gave me:

        linux-vdso.so.1 =>  (0x00007fffbfb8a000)                                                                                                                            
        libsmartpen.so => /usr/lib/libsmartpen.so (0x00007f61fa283000)                                                                                                                           
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f61fa065000)                                                                                                                           
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f61f9c9b000)                                                                                                                           
        libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f61f998c000)                                                                                                                           
        libopenobex.so.1 => /usr/lib/libopenobex.so.1 (0x00007f61f9782000)                                                                                                                           
        libusb-1.0.so.0 => /lib/x86_64-linux-gnu/libusb-1.0.so.0 (0x00007f61f956a000)                                                                                                                           
        /lib64/ld-linux-x86-64.so.2 (0x00007f61fa68c000)                                                                                                                           
        libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f61f92fd000)                                                                                                                            
        libusb-0.1.so.4 => /lib/x86_64-linux-gnu/libusb-0.1.so.4 (0x00007f61f90f4000)                                                                                                                            
        libudev.so.1 => /lib/x86_64-linux-gnu/libudev.so.1 (0x00007f61f8ee1000)

**Comment by barichello** [comment]
no clue?

**Comment by srwalter** [comment]
Do you have a custom version of python installed or anything?  I really
can't think of a reason why you would get that error, all the files seem to
exist...

On Sat, Sep 19, 2015 at 6:01 PM, Leonardo Barichello <
notifications@github.com> wrote:

> no clue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/srwalter/libsmartpen/issues/6#issuecomment-141710471>.
>



-- 
-Steven Walter <stevenrwalter@gmail.com>

**Comment by barichello** [comment]
I dont think I do... I am not a python programmer and I just use it as basic component of my system to make "other things" work.

I tried in two PCS, both with Kubuntu 15.04 (KDE 5) running on.

I will try a third one with kubuntu 14.10 and post back here.

**Comment by barichello** [comment]
a guy found the solution on Kubuntu Forum (https://www.kubuntuforums.net/showthread.php?68973-Problem-with-Python-library-libsmartpen):

Run:
[code]export PYTHONPATH=/usr/lib/pyshared//python2.7/:/usr/share/pyshared/:PYTHONPATH[/code]

Then:
[code]source .bashrc[/code]

It worked for me!
